In [25]:
#Importing libraries
import pandas as pd
from tabulate import tabulate
%pip install matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

Requirement already satisfied: matplotlib in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (3.10.1)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (4.56.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (1.4.8)
Requirement already satisfied: numpy>=1.23 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.2.4)
Requirement already satisfied: packaging>=20.0 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (3.2.3)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\denis\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: C:\Users\denis\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

In [2]:
EconomicDF = pd.read_csv("C:/Users/denis/OneDrive/VSCode/Git/culminating-project-group-2/WEEK 4/EconomicData106.csv")
EnviornmentDF = pd.read_csv("C:/Users/denis/OneDrive/VSCode/Git/culminating-project-group-2/Database/DataSources/World Development Indicators (WDI)/Envirnmental_Indicators.csv")

In [4]:
#Display the first 10 rows of the EconomicDF DataFrame
EconomicDF.head(10)

,Country Name,Country Code,Time,Time Code,Adjusted Net National Income(Yrly % Growth),Adjusted Net Natiobnal Income (Constant),Adjusted Net National Income (Current),Current Account Balance (% GDP),Current Account Balance (BoP Current $),Exports Goods and Services (% GDP),...,Net Official Aid Received (Current $),Net Dvlpmt Assistance and Aid Received (Constant 2021 $),Net Trade in Goods (Current $),Net Trade in Goods and Services (Current $),"Portfolio Investment, Bonds (PPG + PNG) (NFL, Current $)",Net Portfolio Investment (Current $),Service Exports (Current $),Service Imports (Current $),Taxes Less Subsidies on Products (Constant LCU),Travel Services (% of Service Exports)
0,Albania,ALB,2021.0,YR2021,11.05709518,11130019640,14797555219,-7.595907592,-1369694859,31.13302001,...,..,633419982.9,-4513572352,-2392168078,549312000,-92646610.22,4117323974,1995919701,2.09705E+11,54.81856723
1,Albania,ALB,2022.0,YR2022,..,..,..,-5.872436401,-1116775476,37.19708481,...,..,338769989,-4466603020,-1959879935,..,601028649.5,5019488987,2512777696,2.15861E+11,58.91190938
2,Albania,ALB,2023.0,YR2023,..,..,..,-1.196321748,-281700033.3,38.66508179,...,..,..,-4911624604,-1275078201,590952000,349390280.7,7114203250,3477656983,2.11458E+11,63.53535632
3,Argentina,ARG,2021.0,YR2021,12.48955577,4.88631E+11,4.11983E+11,1.361544222,6624785192,18.06670917,...,..,155259994.5,18695465615,14995374117,-1247849000,4940438118,9588735678,13288827176,1.13555E+11,4.111068888
4,Argentina,ARG,2022.0,YR2022,..,..,..,-0.640820188,-4055046517,16.24801444,...,..,407309997.6,12352064402,5529161408,-3188680000,6898955727,14413679146,21236582139,1.20651E+11,24.09877182
5,Argentina,ARG,2023.0,YR2023,..,..,..,-3.243512548,-20955532698,12.74924578,...,..,..,-2936850511,-9352747404,-2613709000,5420481191,16110565249,22526462141,1.18318E+11,34.05417315
6,Armenia,ARM,2021.0,YR2021,2.40277797,10551045918,11228790134,-3.479973958,-482982405.9,35.90643999,...,..,161949996.9,-1504769053,-1115247228,733035000,-672026508.2,1763282838,1373761014,5.42296E+11,44.4739219
7,Armenia,ARM,2022.0,YR2022,..,..,..,0.331693235,64724981.18,50.22498046,...,..,322529998.8,-1865756410,-147212952.4,..,1355929977,4406479991,2687936533,5.86222E+11,55.35242615
8,Armenia,ARM,2023.0,YR2023,..,..,..,-2.309786441,-556329378.3,59.45208567,...,..,..,-2514652434,-193722388.3,-169869000,-64467744.54,5690483460,3369553414,6.50707E+11,52.88284054
9,Australia,AUS,2021.0,YR2021,..,..,1.1741E+12,3.137208512,48838047105,22.05667598,...,..,..,85887678263,89608648118,..,85145403286,45035585027,41314615172,1.49898E+11,37.88562928

In [5]:
#dropping time code and conutry code
EconomicDF = EconomicDF.drop(columns=['Country Code', 'Time Code'])
EconomicDF = EconomicDF.rename(columns={'Country Name': 'Country', 'Time': 'Year'})

In [7]:
#Display info about the EnviornmentDF DataFrame
EconomicDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 318 entries, 0 to 317
Data columns (total 66 columns):
 #   Column                                                                        Non-Null Count  Dtype
---  ------                                                                        --------------  -----
 0   Country                                                                       318 non-null    object
 1   Year                                                                          318 non-null    float64
 2   Adjusted Net National Income(Yrly % Growth)                                   318 non-null    object
 3   Adjusted Net Natiobnal Income (Constant)                                      318 non-null    object
 4   Adjusted Net National Income (Current)                                        318 non-null    object
 5   Current Account Balance (% GDP)                                               318 non-null    object
 6   Current Account Balance (BoP Current $)                                       318 non-null    object
 7   Exports Goods and Services (% GDP)                                            318 non-null    object
 8   Exports Goods and Services (Yrly % growth)                                    318 non-null    object
 9   Exports of Goods and Services (Current $)                                     318 non-null    object
 10  External Balance on Goods and Services (Constant LCU)                         318 non-null    object
 11  Foreign Direct Investment, Net (Current $)                                    318 non-null    object
 12  Foreign Direct Investment, Net Inflows (% of GDP)                             318 non-null    object
 13  Foreign Direct Investment, Net Inflows (Current $)                            318 non-null    float64
 14  Foreign Direct Investment, Net Outflows (% of GDP)                            318 non-null    object
 15  Foreign Direct Investment, Net Outflows (Current $)                           318 non-null    object
 16  GDP (Constant 2015 $)                                                         318 non-null    object
 17  GDP (Constant LCU)                                                            318 non-null    object
 18  GDP (Current LCU)                                                             318 non-null    object
 19  GDP (Current $)                                                               318 non-null    object
 20  GDP Growth (Yrly %)                                                           318 non-null    object
 21  GDP per capita (Constant 2015 $)                                              318 non-null    object
 22  GDP per capita (Constant LCU)                                                 318 non-null    object
 23  GDP per capita (Current LCU)                                                  318 non-null    object
 24  GDP per Capita (Current $)                                                    318 non-null    object
 25  GDP per Capita Growth (Yrly %)                                                318 non-null    object
 26  GDP per capita, PPP (Constant 2021 International $)                           318 non-null    object
 27  GDP per capita, PPP (Current International $)                                 318 non-null    object
 28  GDP, PPP (Constant 2021 International $)                                      318 non-null    object
 29  GDP, PPP (Current International $)                                            318 non-null    object
 30  GDP: Linked Series (Current LCU)                                              318 non-null    object
 31  General Government Final Consumption Expenditure (% of GDP)                   318 non-null    object
 32  General Government Final Consumption Expenditure (Annual % Growth)            318 non-null    object
 33  General Government Final Consumption Expenditure (Current $)                  318 non-null    object
 34  Goods Exports (Current $)                                                     318 non-null    object
 35  Goods Imports (Current $)                                                     318 non-null    object
 36  Grants, Excluding Technical Cooperation (Current $)                           318 non-null    object
 37  Gross Domestic Savings (% GDP)                                                318 non-null    object
 38  Gross Domestic Savings (Current LCU)                                          318 non-null    object
 39  Gross National Expenditure (% of GDP)                                         318 non-null    object
 40  Gross National Expenditure Deflator (Base Yr Varies by Country)               318 non-null    object
 41  Gross Value Added at Basic Prices (GVA) (Constant 2015 $)                     318 non-null    object
 42  Households and NPISHs Final Consumption Expenditure (% of GDP)                318 non-null    object
 43  Households and NPISHs Final Consumption Expenditure (Annual % Growth)         318 non-null    object
 44  Households and NPISHs Final Consumption Expenditure (Current LCU)             318 non-null    object
 45  Imports Goods and Services (% GDP)                                            318 non-null    object
 46  Imports Goods and Services (Yrly % Growth)                                    318 non-null    object
 47  Imports of Goods and Services (Current $)                                     318 non-null    object
 48  Multilateral Debt Service (% of Public and Publicly Guaranteed Debt Service)  318 non-null    object
 49  Net Financial Flows, IBRD (NFL, Current $)                                    318 non-null    object
 50  Net Financial Flows, IDA (NFL, Current $)                                     318 non-null    object
 51  Net Financial Flows, IMF Concessional (NFL, Current $)                        318 non-null    object
 52  Net Financial Flows, IMF Nonconcessional (NFL, Current $)                     318 non-null    object
 53  Net Financial Flows, Multilateral (NFL, Current $)                            318 non-null    object
 54  Net ODA Received (% of Central Government Expense)                            318 non-null    object
 55  Net ODA Received (% of GNI)                                                   318 non-null    object
 56  Net Official Aid Received (Current $)                                         318 non-null    object
 57  Net Dvlpmt Assistance and Aid Received (Constant 2021 $)                      318 non-null    object
 58  Net Trade in Goods (Current $)                                                318 non-null    object
 59  Net Trade in Goods and Services (Current $)                                   318 non-null    object
 60  Portfolio Investment, Bonds (PPG + PNG) (NFL, Current $)                      318 non-null    object
 61  Net Portfolio Investment (Current $)                                          318 non-null    object
 62  Service Exports (Current $)                                                   318 non-null    object
 63  Service Imports (Current $)                                                   318 non-null    object
 64  Taxes Less Subsidies on Products (Constant LCU)                               318 non-null    object
 65  Travel Services (% of Service Exports)                                        318 non-null    object
dtypes: float64(2), object(64)
memory usage: 164.1+ KB

In [8]:
#list variable names in the EconomicDF DataFrame
EconomicDF.columns.tolist()

['Country',
 'Year',
 'Adjusted Net National Income(Yrly % Growth)',
 'Adjusted Net Natiobnal Income (Constant)',
 'Adjusted Net National Income (Current)',
 'Current Account Balance (% GDP)',
 'Current Account Balance (BoP Current $)',
 'Exports Goods and Services (% GDP)',
 'Exports Goods and Services (Yrly % growth)',
 'Exports of Goods and Services (Current $)',
 'External Balance on Goods and Services (Constant LCU)',
 'Foreign Direct Investment, Net (Current $)',
 'Foreign Direct Investment, Net Inflows (% of GDP)',
 'Foreign Direct Investment, Net Inflows (Current $)',
 'Foreign Direct Investment, Net Outflows (% of GDP)',
 'Foreign Direct Investment, Net Outflows (Current $)',
 'GDP (Constant 2015 $)',
 'GDP (Constant LCU)',
 'GDP (Current LCU)',
 'GDP (Current $)',
 'GDP Growth (Yrly %)',
 'GDP per capita (Constant 2015 $)',
 'GDP per capita (Constant LCU)',
 'GDP per capita (Current LCU)',
 'GDP per Capita (Current $)',
 'GDP per Capita Growth (Yrly %)',
 'GDP per capita, PPP (Constant 2021 International $)',
 'GDP per capita, PPP (Current International $)',
 'GDP, PPP (Constant 2021 International $)',
 'GDP, PPP (Current International $)',
 'GDP: Linked Series (Current LCU)',
 'General Government Final Consumption Expenditure (% of GDP)',
 'General Government Final Consumption Expenditure (Annual % Growth)',
 'General Government Final Consumption Expenditure (Current $)',
 'Goods Exports (Current $)',
 'Goods Imports (Current $)',
 'Grants, Excluding Technical Cooperation (Current $)',
 'Gross Domestic Savings (% GDP)',
 'Gross Domestic Savings (Current LCU)',
 'Gross National Expenditure (% of GDP)',
 'Gross National Expenditure Deflator (Base Yr Varies by Country)',
 'Gross Value Added at Basic Prices (GVA) (Constant 2015 $)',
 'Households and NPISHs Final Consumption Expenditure (% of GDP)',
 'Households and NPISHs Final Consumption Expenditure (Annual % Growth)',
 'Households and NPISHs Final Consumption Expenditure (Current LCU)',
 'Imports Goods and Services (% GDP)',
 'Imports Goods and Services (Yrly % Growth)',
 'Imports of Goods and Services (Current $)',
 'Multilateral Debt Service (% of Public and Publicly Guaranteed Debt Service)',
 'Net Financial Flows, IBRD (NFL, Current $)',
 'Net Financial Flows, IDA (NFL, Current $)',
 'Net Financial Flows, IMF Concessional (NFL, Current $)',
 'Net Financial Flows, IMF Nonconcessional (NFL, Current $)',
 'Net Financial Flows, Multilateral (NFL, Current $)',
 'Net ODA Received (% of Central Government Expense)',
 'Net ODA Received (% of GNI)',
 'Net Official Aid Received (Current $)',
 'Net Dvlpmt Assistance and Aid Received (Constant 2021 $)',
 'Net Trade in Goods (Current $)',
 'Net Trade in Goods and Services (Current $)',
 'Portfolio Investment, Bonds (PPG + PNG) (NFL, Current $)',
 'Net Portfolio Investment (Current $)',
 'Service Exports (Current $)',
 'Service Imports (Current $)',
 'Taxes Less Subsidies on Products (Constant LCU)',
 'Travel Services (% of Service Exports)']

In [11]:
# Create a new DataFrame with the columns of interest that exist in EconomicDF
# Ensure the column names exist in the DataFrame
columnsInterest = ['Country', 'Year', 'GDP (Current $)', 'GDP Growth (Yrly %)', 'GDP per Capita (Current $)', 'Adjusted Net National Income(Yrly % Growth)',
 'Adjusted Net Natiobnal Income (Constant)', 'Adjusted Net National Income (Current)', 'Service Exports (Current $)', 'Service Imports (Current $)']
EconomicDF = EconomicDF[columnsInterest]

In [12]:
#number of columns ib EconomicDF DataFrame
EconomicDF.shape # Display the number of columns in the EconomicDF DataFrame

(318, 10)

In [13]:
#Display information about the EconomicDF DataFrame
EnviornmentDF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 803 entries, 0 to 802
Data columns (total 11 columns):
 #   Column                                                                                             Non-Null Count  Dtype
---  ------                                                                                             --------------  -----
 0   Country Name                                                                                       800 non-null    object
 1   Country Code                                                                                       798 non-null    object
 2   Time                                                                                               798 non-null    float64
 3   Time Code                                                                                          798 non-null    object
 4   Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990) [EN.GHG.CO2.ZG.AR5]   798 non-null    object
 5   Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e) [EN.GHG.CO2.MT.CE.AR5]           798 non-null    object
 6   Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita) [EN.GHG.CO2.PC.CE.AR5]  798 non-null    object
 7   Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS]                798 non-null    object
 8   Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]                           798 non-null    object
 9   Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]                           798 non-null    object
 10  Forest area (sq. km) [AG.LND.FRST.K2]                                                              798 non-null    object
dtypes: float64(1), object(10)
memory usage: 69.1+ KB

In [14]:
#drop time code and conutry code
EnviornmentDF = EnviornmentDF.drop(columns=['Country Code', 'Time Code'])
EnviornmentDF = EnviornmentDF.rename(columns={'Country Name': 'Country', 'Time': 'Year'})

In [17]:
# Handle NaN values in the Year column before converting to float
EnviornmentDF['Year'] = EnviornmentDF['Year'].fillna(0).astype(float).astype(int)

In [20]:
#removing countries that are not part of prechosen 106 countries
specifiedCountries = ['Albania', 'Argentina', 'Armenia', 'Australia', 'Austria', 
                      'Bangladesh', 'Barbados', 'Belgium', 'Bolivia', 'Bosnia and Herzegovina', 
                      'Botswana', 'Brazil', 'Bulgaria', 'Burkina Faso', 'Cambodia', 'Canada', 'Chile', 'China', 'Colombia', 
                      'Congo, Dem. Rep.', 'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cyprus', 'Czechia', 'Denmark', 'Dominican Republic', 
                      'El Salvador', 'Estonia', 'Fiji', 'Finland', 'France', 'Georgia', 'Germany', 'Greece', 'Guatemala', 'Honduras', 
                      'Hungary', 'Iceland', 'Indonesia', 'Ireland', 'Israel', 'Italy', 'Japan', 'Kazakhstan', 'Kenya', 'Korea, Rep.', 'Kosovo',
                      'Kyrgyz Republic', 'Latvia', 'Lebanon', 'Lesotho', 'Lithuania', 'Luxembourg', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives',
                      'Malta', 'Mauritius', 'Mexico', 'Moldova', 'Mongolia', 'Morocco', 'Nepal', 'Netherlands', 'New Zealand', 'Nicaragua', 'Nigeria', 
                      'North Macedonia', 'Norway', 'Pakistan', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal', 'Romania',
                      'Russian Federation', 'Rwanda', 'Saudi Arabia', 'Senegal', 'Serbia', 'Seychelles', 'Slovak Republic', 'Slovenia', 
                      'Solomon Islands', 'South Africa', 'Spain', 'Sri Lanka', 'St. Lucia', 'Suriname', 'Sweden', 'Switzerland', 'Tajikistan', 
                      'Tanzania', 'Thailand', 'Timor-Leste', 'Togo', 'Tonga', 'Turkiye', 'Uganda', 'United Kingdom', 'United States', 'Uruguay']

#Filter the data to include only the specified countries
EnviornmentDF = EnviornmentDF[EnviornmentDF['Country'].isin(specifiedCountries)]

In [21]:
#Displaying the count of unique items in the 'Country Name' column
print(f'Unique Country Name column: {EnviornmentDF["Country"].nunique()}')

Unique Country Name column: 106

In [22]:
#identifying data types and missing values in one table
#Get the data types
dtypes = EnviornmentDF.dtypes

# Get the number of missing values
missingValues = EnviornmentDF.isna().sum()

#Creating a new DataFrame for combined information
info = pd.DataFrame({'Column': dtypes.index,'DataType': dtypes.values,'MissingValues': missingValues.values})

#Converting DataFrame to table format with right alignment
table = tabulate(info, headers='keys', tablefmt='pretty', showindex=False, colalign=("right", "right", "right"))
print(table)

+---------------------------------------------------------------------------------------------------+----------+---------------+
|                                                                                            Column | DataType | MissingValues |
+---------------------------------------------------------------------------------------------------+----------+---------------+
|                                                                                           Country |   object |             0 |
|                                                                                              Year |    int64 |             0 |
|  Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990) [EN.GHG.CO2.ZG.AR5] |   object |             0 |
|          Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e) [EN.GHG.CO2.MT.CE.AR5] |   object |             0 |
| Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita) [EN.GHG.CO2.PC.CE.AR5] |   object |             0 |
|               Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS] |   object |             0 |
|                          Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS] |   object |             0 |
|                          Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS] |   object |             0 |
|                                                             Forest area (sq. km) [AG.LND.FRST.K2] |   object |             0 |
+---------------------------------------------------------------------------------------------------+----------+---------------+

In [23]:
#convert columns except for 'Country' and 'Year' to numeric
EnviornmentDF.iloc[:, 2:] = EnviornmentDF.iloc[:, 2:].apply(pd.to_numeric, errors='coerce')
# Display the first 10 rows of the EnviornmentDF DataFrame after conversion
EnviornmentDF.head(10)

,Country,Year,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990) [EN.GHG.CO2.ZG.AR5],Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e) [EN.GHG.CO2.MT.CE.AR5],Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita) [EN.GHG.CO2.PC.CE.AR5],Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Forest area (sq. km) [AG.LND.FRST.K2]
3,Albania,2021,-24.164033,5.0393,1.792283,41.9,100.0,100.0,7889.0
4,Albania,2022,-30.639579,4.609,1.659293,NaN,100.0,100.0,7889.0
5,Albania,2023,-30.89842,4.5918,1.672195,NaN,NaN,NaN,NaN
21,Argentina,2021,90.304988,190.662,4.207733,9.2,100.0,100.0,284636.667
22,Argentina,2022,93.119308,193.4816,4.260967,NaN,100.0,100.0,283552.222
23,Argentina,2023,83.434277,183.7784,4.03568,NaN,NaN,NaN,NaN
24,Armenia,2021,-63.863504,7.5092,2.534922,9.1,100.0,99.9,3282.6
25,Armenia,2022,-64.921728,7.2893,2.454971,NaN,100.0,100.0,3280.5
26,Armenia,2023,-62.824529,7.7251,2.582868,NaN,NaN,NaN,NaN
30,Australia,2021,38.516443,384.6772,14.976485,12.3,100.0,100.0,1340051.0

In [24]:
#filling missing values with 0
EnviornmentDF = EnviornmentDF.fillna(0)

#Display the first 10 rows of the EnviornmentDF
EnviornmentDF.head(10)

C:\Users\denis\AppData\Local\Temp\ipykernel_30536\2414126219.py:2: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  EnviornmentDF = EnviornmentDF.fillna(0)

,Country,Year,Carbon dioxide (CO2) emissions (total) excluding LULUCF (% change from 1990) [EN.GHG.CO2.ZG.AR5],Carbon dioxide (CO2) emissions (total) excluding LULUCF (Mt CO2e) [EN.GHG.CO2.MT.CE.AR5],Carbon dioxide (CO2) emissions excluding LULUCF per capita (t CO2e/capita) [EN.GHG.CO2.PC.CE.AR5],Renewable energy consumption (% of total final energy consumption) [EG.FEC.RNEW.ZS],"Access to electricity, rural (% of rural population) [EG.ELC.ACCS.RU.ZS]","Access to electricity, urban (% of urban population) [EG.ELC.ACCS.UR.ZS]",Forest area (sq. km) [AG.LND.FRST.K2]
3,Albania,2021,-24.164033,5.0393,1.792283,41.9,100.0,100.0,7889.000
4,Albania,2022,-30.639579,4.6090,1.659293,0.0,100.0,100.0,7889.000
5,Albania,2023,-30.898420,4.5918,1.672195,0.0,0.0,0.0,0.000
21,Argentina,2021,90.304988,190.6620,4.207733,9.2,100.0,100.0,284636.667
22,Argentina,2022,93.119308,193.4816,4.260967,0.0,100.0,100.0,283552.222
23,Argentina,2023,83.434277,183.7784,4.035680,0.0,0.0,0.0,0.000
24,Armenia,2021,-63.863504,7.5092,2.534922,9.1,100.0,99.9,3282.600
25,Armenia,2022,-64.921728,7.2893,2.454971,0.0,100.0,100.0,3280.500
26,Armenia,2023,-62.824529,7.7251,2.582868,0.0,0.0,0.0,0.000
30,Australia,2021,38.516443,384.6772,14.976485,12.3,100.0,100.0,1340051.000